### ISSUE TITLE
Falha na exportação para CSV

### ISSUE THREAD

**Issue by vitormattos** [LibreCodeCoop/producao-cooperativista#50]
Após converter as entidades de array para objeto, a exportação destes dados para CSV parou de funcionar.

Qualquer comando `get` com a opção `--csv` dá o erro que segue:

Necessário implementar conversão de objeto para array.

```
Fatal error: Uncaught TypeError: array_keys(): Argument #1 ($array) must be of type array, ProducaoCooperativista\DB\Entity\Invoices given in /app/src/Command/BaseCommand.php:57
Stack trace:
#0 /app/src/Command/BaseCommand.php(57): array_keys(Object(ProducaoCooperativista\DB\Entity\Invoices))
#1 /app/src/Command/GetInvoicesCommand.php(87): ProducaoCooperativista\Command\BaseCommand->toCsv(Array)
#2 /app/vendor/symfony/console/Command/Command.php(326): ProducaoCooperativista\Command\GetInvoicesCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#3 /app/vendor/symfony/console/Application.php(1063): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#4 /app/vendor/symfony/console/Application.php(320): Symfony\Component\Console\Application->doRunCommand(Object(ProducaoCooperativista\Command\GetInvoicesCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#5 /app/vendor/symfony/console/Application.php(174): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#6 /app/bin/import.php(102): Symfony\Component\Console\Application->run()
#7 /app/bin/import(25): require('/app/bin/import...')
#8 {main}
  thrown in /app/src/Command/BaseCommand.php on line 57
```

Para identificar os comandos `get`'s execute: `./bin/import get`

**Comment by DaianeAlvesRJ** [comment]
https://github.com/LibreCodeCoop/producao-cooperativista/issues/38

**Comment by DaianeAlvesRJ** [comment]
https://github.com/LibreCodeCoop/my_company/issues/19

**Comment by DaianeAlvesRJ** [comment]
@vitormattos isso é referente a quê?

**Comment by vitormattos** [comment]
Existe a exportação para CSV mas não está sendo utilizada no momento. Não é algo que nos impacta.

**Comment by vitormattos** [comment]
Exportação não está mais sendo usada.
